# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f963ad41c45a31b60c2e407da18fb951bdfa9af2743561cce5b435ca0da4ea3a472f177fd68a715d82a1b6017ff8b41a741d203959a8a07dddde6280d5a6d1ea

test:
  secret_key_base: 7f0883e008a46d9be0e43f53cc1db4ad77f52d830797435621573631adf1e20845b7a20a916d70b629d12630f7f641f0aeb527bebdef04838ae6a4e957283032

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
